name: dds
description: >-
  A library used to spawn the Dart Developer Service, used to communicate with
  a Dart VM Service instance.

version: 0.1.0-dev

homepage: https://github.com/dart-lang/sdk/tree/master/pkg/dds

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  json_rpc_2: ^2.1.0
  shelf: ^0.7.5
  shelf_proxy: ^0.1.0+7
  shelf_web_socket: ^0.2.3
  web_socket_channel: ^1.1.0

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.0.0
  vm_service: ^4.0.0
