include: package:pedantic/analysis_options.1.9.0.yaml

analyzer:
  errors:
    # Increase the severity of several hints.
    prefer_single_quotes: warning
    unused_import: warning
    unnecessary_brace_in_string_interps: warning

    # Ignore one pedantic lint
    omit_local_variable_types: ignore

linter:
  rules:
    - directives_ordering
    - prefer_relative_imports
    - unnecessary_brace_in_string_interps
