name: dartdev

# This package is not intended to be published
publish_to: none

environment:
  sdk: '>=2.6.0 <3.0.0'
dependencies:
  args: ^1.6.0
  cli_util: ^0.1.4
  dds:
    path: '../dds'
  intl: ^0.16.1
  path: ^1.0.0
  stack_trace: ^1.9.3
  stagehand: 3.3.7
  usage: ^3.4.0
  watcher: ^0.9.6
  yaml: ^2.2.0

dev_dependencies:
  test: ^1.0.0
  pedantic: ^1.9.0
