# This pubspec is currently mainly used to make it easier to develop on the
# gardening by making it a package.
name: gardening
#version: do-not-upload
environment:
  sdk: "^2.7.0"
dependencies:
  args:
  http:
  path:
  status_file:
    path: ../../pkg/status_file/
  expect:
    path: ../../pkg/expect/
  testing:
    path: ../../pkg/testing/
