include: package:pedantic/analysis_options.1.8.0.yaml

analyzer:
  strong-mode:
    implicit-casts: false
  errors:
    todo: ignore
  exclude:
    - doc/api/**
    - gen/**
    - node_modules/**
    - test/codegen/**
    - test/samples/**
    - test/transformer/hello_app/**

linter:
  rules:
    - always_declare_return_types
    - annotate_overrides
    - prefer_conditional_assignment
    - prefer_null_aware_operators
    - prefer_single_quotes
    # Not enforced by pedantic at any version
    - directives_ordering
    - prefer_typing_uninitialized_variables
