linter:
  rules:
    - empty_constructor_bodies # pedantic
    - empty_statements
    - prefer_equal_for_default_values # pedantic
    - unnecessary_brace_in_string_interps
    - valid_regexps # pedantic
