name: js
version: 0.6.2-dev
description: Annotations to create Dart interfaces for JavaScript APIs.
homepage: https://github.com/dart-lang/sdk/tree/master/pkg/js

environment:
  sdk: '>=2.9.0 <3.0.0'
