name: js
version: 0.6.3-nullsafety
description: Annotations to create static Dart interfaces for JavaScript APIs.
homepage: https://github.com/dart-lang/sdk/tree/master/pkg/js

environment:
  # This must remain a tight constraint until nnbd is stable
  sdk: '>=2.10.0-0 <2.10.0'

dev_dependencies:
  pedantic: ^1.9.0
