name: js
version: 0.6.4
author: Dart Team <misc@dartlang.org>
description: Access JavaScript from Dart.
homepage: https://github.com/dart-lang/sdk/tree/master/pkg/js

environment:
  sdk: '>=2.9.0 <3.0.0'
