name: meta
version: 1.2.0-dev
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/sdk/tree/master/pkg/meta
description: >
 This library contains the definitions of annotations that provide additional
 semantic information about the program being annotated. These annotations are
 intended to be used by tools to provide a better user experience.
environment:
  sdk: '>=2.8.0-dev.10 <3.0.0'
